#!/usr/bin/env python3
"""Regenerate scripts/signing-requirements.txt from PyPI.

Every artifact of each pinned version is listed by hash, so pip can pick the
wheel that fits the host while --require-hashes still refuses anything whose
content does not match. Bump a version below, run this, and read the
changelog before committing the result.
"""
import json
import pathlib
import urllib.request

PINS = {"cryptography": "50.0.0", "cffi": "2.1.1", "pycparser": "3.0"}

HEADER = """\
# Pinned inputs for the TA signing venv, by version and by hash.
#
# scripts/build-uboot.sh installs this with --require-hashes, so pip refuses
# anything whose content does not match. The signing step runs as the user who
# owns the TA private key, so whatever pip installs runs with permission to
# read it - an unpinned install makes that a supply-chain question with a new
# answer every build.
#
# Generated by scripts/regen-signing-requirements.py. Do not edit by hand.
"""


def files_for(pkg, ver):
    url = f"https://pypi.org/pypi/{pkg}/{ver}/json"
    with urllib.request.urlopen(url) as r:
        data = json.load(r)
    return sorted(data["urls"], key=lambda f: f["filename"])


def main():
    out = [HEADER]
    for pkg, ver in PINS.items():
        hashes = [f"    --hash=sha256:{f['digests']['sha256']}"
                  for f in files_for(pkg, ver)]
        out.append(f"{pkg}=={ver} \\\n" + " \\\n".join(hashes) + "\n")
    dest = pathlib.Path(__file__).with_name("signing-requirements.txt")
    dest.write_text("\n".join(out))
    print(f"wrote {dest} ({sum(1 for l in dest.read_text().splitlines() if '--hash' in l)} hashes)")


if __name__ == "__main__":
    main()
