#!/bin/bash
# Delete old portable-artifact tarballs from the Nerves build volume.
#
# Every system build writes nerves_system_sige5-portable-<version>-<hash>.tar.gz
# into the build volume. They are ~390 MB each, and with nothing removing them
# a few weeks of iteration was tens of gigabytes: 104 of them, 39 GB.
#
# post-createfs.sh now clears them during the build, so this is for tidying a
# volume without running one - after switching branches, or when
# `container system df` looks wrong.
#
# The volume's backing file is sparse and grows to its high-water mark, and the
# guest's virtio-blk device does not support discard - fstrim returns
# "FITRIM ioctl failed: Operation not permitted" even with CAP_SYS_ADMIN. So
# deleting files inside does not shrink the file on the host; it frees blocks
# for the next build to reuse, which is what stops it growing. Reclaiming the
# high-water mark means deleting the volume and rebuilding from scratch.
#
# The default is 1, not 3. The artifact that matters is copied out to
# ~/.nerves/artifacts/ during the build and is what firmware builds actually
# use, so the copies left inside the volume are duplicates. Keeping one is a
# convenience; keeping several is just spending disk to no end.
#
#     tools/prune-build-volume.sh          # keep the newest
#     KEEP=0 tools/prune-build-volume.sh   # remove all of them
#     KEEP=3 tools/prune-build-volume.sh   # keep the 3 newest
set -euo pipefail

KEEP=${KEEP:-1}
IMG=${NERVES_BR_IMAGE:-ghcr.io/nerves-project/nerves_system_br:1.34.0}
VOL=${NERVES_BUILD_VOLUME:-$(container volume ls 2>/dev/null |
	awk '$1 ~ /^nerves_system_sige5-/ && $1 !~ /-platform$/ { print $1; exit }')}

[ -n "$VOL" ] || { echo "no build volume found (set NERVES_BUILD_VOLUME)" >&2; exit 1; }
echo "volume: $VOL, keeping $KEEP newest"

container run --rm -v "$VOL":/work "$IMG" sh -c '
set -u
keep=$1
cd /work || exit 0
before=$(df -h /work | awk "NR==2 {print \$3}")
total=$(ls -t nerves_system_*-portable-*.tar.gz 2>/dev/null | wc -l)
ls -t nerves_system_*-portable-*.tar.gz 2>/dev/null | tail -n +$((keep + 1)) | xargs -r rm -f
# Regenerated by every build and never read afterwards.
rm -rf legal-info
after=$(df -h /work | awk "NR==2 {print \$3}")
removed=$((total > keep ? total - keep : 0))
echo "removed $removed of $total artifacts; $before used -> $after used"
' _ "$KEEP"
